name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: g++ -std=c++11 -Wall FlashCard.cpp -o FlashCard
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: app-linux
        path: |
          FlashCard
          Neuro*
          
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: g++ -std=c++11 -Wall FlashCard.cpp -o FlashCard
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: app-windows
        path: |
          FlashCard.exe
          Neuro*
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        # Artifact name
        name: app-linux
        # Destination path
        path: app-linux
    - name: Download a Build Artifact2
      uses: actions/download-artifact@v2.0.8
      with:
        # Artifact name
        name: app-windows
        # Destination path
        path: app-windows
    - name: Create Zip
      run: zip -r app-linux.zip app-linux
    - name: Create Zip2
      run: zip -r app-windows.zip app-windows
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
      uses: ncipollo/release-action@v1.7.3
      with:
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        allowUpdates: true
        artifacts: app-linux.zip,app-windows.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v2.0.0
