name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: g++ -std=c++11 -Wall FlashCard.cpp -o FlashCard
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: app-linux
        path: |
          FlashCard
          Neuro*
          
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: g++ -std=c++11 -Wall FlashCard.cpp -o FlashCard
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: app-windows
        path: |
          FlashCard
          Neuro*
